name: "Treewide Checks"
permissions: read-all

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  check-format-with-alejandra:
    name: "Check formatting"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Check formatting via Alejandra
        run: nix run nixpkgs#alejandra -- -c .
