name: "Treewide Checks"
permissions: read-all

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  nix-flake-check:
    name: "Validate flake"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Check if the Flake can build
        run: nix flake check --all-systems

  check-format:
    name: "Check formatting"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Check formatting via alejandra(for nix) and stylua(lua)
        run: |
          nix-shell -p alejandra -p stylua --run \
            'alejandra -c . && stylua --no-editorconfig --indent-width 2 --indent-type Spaces --quote-style ForceSingle --check .'
